### ISSUE TITLE
EXTBAN example missing prefix

### ISSUE THREAD

**Issue by Herringway** [DanielOaks/irc-defs#18]
One of the EXTBAN examples in the RPL_ISUPPORT tokens doc is missing a prefix character. However, the description for the token does not explain how a client is meant to interpret this case.

**Comment by sadiepowell** [comment]
No prefix means that extbans do not have a prefix.

InspIRCd sends this as it does not prefix extbans.

**Comment by DanielOaks** [comment]
fix'd with jackal's changes!
